module.exports = [
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group A",
    country: "International",
    team_id: "14778",
    team_name: "Russia",
    status: "same",
    recent_form: "W",
    position: "1",
    overall_gp: "1",
    overall_w: "1",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "5",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "+5",
    points: "3",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group A",
    country: "International",
    team_id: "17412",
    team_name: "Uruguay",
    status: "same",
    recent_form: "W",
    position: "2",
    overall_gp: "1",
    overall_w: "1",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "1",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "+1",
    points: "3",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group A",
    country: "International",
    team_id: "8878",
    team_name: "Egypt",
    status: "same",
    recent_form: "L",
    position: "3",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "0",
    overall_l: "1",
    overall_gs: "0",
    overall_ga: "1",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "-1",
    points: "0",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group A",
    country: "International",
    team_id: "14987",
    team_name: "Saudi Arabia",
    status: "same",
    recent_form: "L",
    position: "4",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "0",
    overall_l: "1",
    overall_gs: "0",
    overall_ga: "5",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "-5",
    points: "0",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group B",
    country: "International",
    team_id: "11442",
    team_name: "Iran",
    status: "same",
    recent_form: "W",
    position: "1",
    overall_gp: "1",
    overall_w: "1",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "1",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "+1",
    points: "3",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group B",
    country: "International",
    team_id: "14227",
    team_name: "Portugal",
    status: "same",
    recent_form: "D",
    position: "2",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "1",
    overall_l: "0",
    overall_gs: "3",
    overall_ga: "3",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "1",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group B",
    country: "International",
    team_id: "15622",
    team_name: "Spain",
    status: "same",
    recent_form: "D",
    position: "3",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "1",
    overall_l: "0",
    overall_gs: "3",
    overall_ga: "3",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "1",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group B",
    country: "International",
    team_id: "13094",
    team_name: "Morocco",
    status: "same",
    recent_form: "L",
    position: "4",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "0",
    overall_l: "1",
    overall_gs: "0",
    overall_ga: "1",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "-1",
    points: "0",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group C",
    country: "International",
    team_id: "9815",
    team_name: "France",
    status: "same",
    recent_form: "W",
    position: "1",
    overall_gp: "1",
    overall_w: "1",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "2",
    overall_ga: "1",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "+1",
    points: "3",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group C",
    country: "International",
    team_id: "8671",
    team_name: "Denmark",
    status: "same",
    recent_form: "W",
    position: "2",
    overall_gp: "1",
    overall_w: "1",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "1",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "+1",
    points: "3",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group C",
    country: "International",
    team_id: "6135",
    team_name: "Australia",
    status: "same",
    recent_form: "L",
    position: "3",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "0",
    overall_l: "1",
    overall_gs: "1",
    overall_ga: "2",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "-1",
    points: "0",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group C",
    country: "International",
    team_id: "13898",
    team_name: "Peru",
    status: "same",
    recent_form: "L",
    position: "4",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "0",
    overall_l: "1",
    overall_gs: "0",
    overall_ga: "1",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "-1",
    points: "0",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group D",
    country: "International",
    team_id: "8243",
    team_name: "Croatia",
    status: "same",
    recent_form: "W",
    position: "1",
    overall_gp: "1",
    overall_w: "1",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "2",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "+2",
    points: "3",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group D",
    country: "International",
    team_id: "11262",
    team_name: "Iceland",
    status: "same",
    recent_form: "D",
    position: "2",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "1",
    overall_l: "0",
    overall_gs: "1",
    overall_ga: "1",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "1",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group D",
    country: "International",
    team_id: "5886",
    team_name: "Argentina",
    status: "same",
    recent_form: "D",
    position: "3",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "1",
    overall_l: "0",
    overall_gs: "1",
    overall_ga: "1",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "1",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group D",
    country: "International",
    team_id: "13584",
    team_name: "Nigeria",
    status: "same",
    recent_form: "L",
    position: "4",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "0",
    overall_l: "1",
    overall_gs: "0",
    overall_ga: "2",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "-2",
    points: "0",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group E",
    country: "International",
    team_id: "15152",
    team_name: "Serbia",
    status: "same",
    recent_form: "W",
    position: "1",
    overall_gp: "1",
    overall_w: "1",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "1",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "+1",
    points: "3",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group E",
    country: "International",
    team_id: "16598",
    team_name: "Switzerland",
    status: "same",
    recent_form: "D",
    position: "2",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "1",
    overall_l: "0",
    overall_gs: "1",
    overall_ga: "1",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "1",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group E",
    country: "International",
    team_id: "7084",
    team_name: "Brazil",
    status: "same",
    recent_form: "D",
    position: "3",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "1",
    overall_l: "0",
    overall_gs: "1",
    overall_ga: "1",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "1",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group E",
    country: "International",
    team_id: "8182",
    team_name: "Costa Rica",
    status: "same",
    recent_form: "L",
    position: "4",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "0",
    overall_l: "1",
    overall_gs: "0",
    overall_ga: "1",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "-1",
    points: "0",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group F",
    country: "International",
    team_id: "12909",
    team_name: "Mexico",
    status: "same",
    recent_form: "W",
    position: "1",
    overall_gp: "1",
    overall_w: "1",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "1",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "+1",
    points: "3",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group F",
    country: "International",
    team_id: "16400",
    team_name: "Sweden",
    status: "same",
    recent_form: "",
    position: "2",
    overall_gp: "0",
    overall_w: "0",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "0",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "0",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group F",
    country: "International",
    team_id: "12303",
    team_name: "South Korea",
    status: "same",
    recent_form: "",
    position: "3",
    overall_gp: "0",
    overall_w: "0",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "0",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "0",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group F",
    country: "International",
    team_id: "10245",
    team_name: "Germany",
    status: "same",
    recent_form: "L",
    position: "4",
    overall_gp: "1",
    overall_w: "0",
    overall_d: "0",
    overall_l: "1",
    overall_gs: "0",
    overall_ga: "1",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "-1",
    points: "0",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group G",
    country: "International",
    team_id: "6737",
    team_name: "Belgium",
    status: "same",
    recent_form: "",
    position: "1",
    overall_gp: "0",
    overall_w: "0",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "0",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "0",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group G",
    country: "International",
    team_id: "8981",
    team_name: "England",
    status: "same",
    recent_form: "",
    position: "2",
    overall_gp: "0",
    overall_w: "0",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "0",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "0",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group G",
    country: "International",
    team_id: "16913",
    team_name: "Tunisia",
    status: "same",
    recent_form: "",
    position: "3",
    overall_gp: "0",
    overall_w: "0",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "0",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "0",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group G",
    country: "International",
    team_id: "13849",
    team_name: "Panama",
    status: "same",
    recent_form: "",
    position: "4",
    overall_gp: "0",
    overall_w: "0",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "0",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "0",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group H",
    country: "International",
    team_id: "13953",
    team_name: "Poland",
    status: "same",
    recent_form: "",
    position: "1",
    overall_gp: "0",
    overall_w: "0",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "0",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "0",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group H",
    country: "International",
    team_id: "8117",
    team_name: "Colombia",
    status: "same",
    recent_form: "",
    position: "2",
    overall_gp: "0",
    overall_w: "0",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "0",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "0",
    description: "Promotion - World Cup (Play Offs)"
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group H",
    country: "International",
    team_id: "15132",
    team_name: "Senegal",
    status: "same",
    recent_form: "",
    position: "3",
    overall_gp: "0",
    overall_w: "0",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "0",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "0",
    description: ""
    },
    {
    comp_id: "1056",
    season: "2018",
    round: "1",
    stage_id: "10561027",
    comp_group: "Group H",
    country: "International",
    team_id: "12124",
    team_name: "Japan",
    status: "same",
    recent_form: "",
    position: "4",
    overall_gp: "0",
    overall_w: "0",
    overall_d: "0",
    overall_l: "0",
    overall_gs: "0",
    overall_ga: "0",
    home_gp: "",
    home_w: "",
    home_d: "",
    home_l: "",
    home_gs: "",
    home_ga: "",
    away_gp: "",
    away_w: "",
    away_d: "",
    away_l: "",
    away_gs: "",
    away_ga: "",
    gd: "0",
    points: "0",
    description: ""
    }
    ];